### ISSUE TITLE
Feature request: static API Key

### ISSUE THREAD

**Issue by steamorchid** [OpenBMB/ChatDev#116]
would be great to set the OPEN_AI_API in .env or another config file

**Comment by yraen69** [comment]
In utils.py you could tweak this function

 def openai_api_key_required

To just return the static key easily enough?

**Comment by indravardhanreddy** [comment]
Did anything work for you??.. I have issue with setting env variable in windows..

> would be great to set the OPEN_AI_API in .env or another config file

**Comment by Solobearus** [comment]
please add this feature... 

> In utils.py you could tweak this function
> 
> def openai_api_key_required
> 
> To just return the static key easily enough?

can you maybe explain this for non python devs?

**Comment by Kaotic3** [comment]
When you clone the repository, you will have a set of folders, one of those folders is "camel"

Within that folder is a file called utils.py - within that is a function called openai_api_key_required.

Within that function is a reference to the OPENAI_API_KEY - which you can change from looking for an os.environ variable to being a static variable.

Now if someone could be so kind as to tell me where the Endpoint is so that I could change that...

**Comment by PhDave13** [comment]
> When you clone the repository, you will have a set of folders, one of those folders is "camel"
> 
> Within that folder is a file called utils.py - within that is a function called openai_api_key_required.
> 
> Within that function is a reference to the OPENAI_API_KEY - which you can change from looking for an os.environ variable to being a static variable.
> 
> Now if someone could be so kind as to tell me where the Endpoint is so that I could change that...

Not a python dev, but a .net C# architect.  I'm also having issues with setting the environment variable on Windows for the API key.  I thought I was just dumb but happy to see others more intelligent than me having the same problem.

Happy to do some digging if you can tell me what you're looking for in terms of Endpoint?

**Comment by Elliot-Construct** [comment]
Surely just creating a .env file with the variable works with os.environ?

**Comment by Kaotic3** [comment]
The issue is more that it is coded deep inside the repo - I found it and updated it, but got an SSL (not related to this project another issue) - so not sure if that is the only place it was coded.

The url used is the OpenAI URL - so changing a .env file doesn't really get to that? It will still use that hardcoded URL right?

Like the previous poster - C# dev here - not entirely useless in python but hardly my best language.

**Comment by konsumer** [comment]
Environment-variables are a very standard way to configure things for software, and is not specific to python. I think you should add it to your environment, separately.

On mac/linux I add a line that looks like this to my shell config (`~/.zshrc`):

```
export OPENAI_API_KEY="MYKEYHERE"
```

For windows, [here](https://phoenixnap.com/kb/windows-set-environment-variable) is info on how to set environment-variables.
