### ISSUE TITLE
feature request: iterative design & testing

### ISSUE THREAD

**Issue by steamorchid** [OpenBMB/ChatDev#117]
In th current version of ChatDev, when the manual is written, the program exits. It would be good to have an option not to exit but to pause, giving the user time to actually test the application. Then, the user could choose if to exit or to go back to the team and have them continue working on the same application.

**Comment by NicoloNava** [comment]
it can can do the "pause for human testing" if you add the parameter --"Human" when running, and in the .json of the human mode phases, i suggests you to put the tests before the human inputs and after them, the optimal would be a test before, a test after EVERY human prompt, and not only before, and after all human inputs. but for now simple and complex  phases cannot be nested together.

Anyway with "resuming from were we left"  (in developing frome the team as I can read), and the possibility to AUTOMATICALLY test guis/functionalities (knowing  and tracking the expected behavior and the actual behavior at runtime to adjust the code, not only watching the simple compiler results at compilation), the project will be fantastic for any coder, maybe in a year when the llms will be cheaper and will have 100k context (like claude 2 100k now), it will also manage enormous projects with efficiency.

**Comment by mowliv** [comment]
@NicoloNava Thanks -- and would you explain in more detail how to do this? 

> put the compiler tests before the human inputs and after them

**Comment by Alphamasterliu** [comment]
Hello! You might want to try adding --config "Human" at the beginning of the "--task" stage to enter the Human-Agent-Interaction mode. This way, you can test the effect of optimizing prompts by interacting with the main.py before software production. I hope this feature helps you overcome your challenges. Thank you very much for trying out ChatDev, and feel free to reach out if you have any questions.
