### ISSUE TITLE
Missing 'main.py' and Other Files in the 'timer' Project

### ISSUE THREAD

**Issue by anokilles** [OpenBMB/ChatDev#120]
when I run the command python3 run.py --task "develop a simple timer" --name "timer", it doesn't generate the 'main.py' and other necessary files for the timer app. Currently, the repository for timer in WareHouse only has these files:

ChatChainConfig.json
PhaseConfig.json
RoleConfig.json
timer.prompt

**Comment by Alphamasterliu** [comment]
You might want to check in your terminal to see if you have successfully configured the OpenAI API key (STEP 4 in Quickstart), or see if the ChatChain Visualizer of the web page you ran through shows the virtual software company in full operation, as this is often the case because the GPT isn't functioning resulting in the Agent not being able to produce the communication.

Thank you for your support and trying out ChatDev, feel free to ask any questions you may have.
