### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by verma-o** [OpenBMB/ChatDev#123]
**When giving command : python run.py --task "random video" --name "myfirst"**

Below output error is coming.

$ python run.py --task "random video" --name "myfirst"
Traceback (most recent call last):
  File "run.py", line 24, in <module>
    from chatdev.chat_chain import ChatChain
  File "C:\Users\youli\GitProject\ChatDev\chatdev\chat_chain.py", line 12, in <module>
    from chatdev.chat_env import ChatEnv, ChatEnvConfig
  File "C:\Users\youli\GitProject\ChatDev\chatdev\chat_env.py", line 35, in <module>
    class ChatEnv:
  File "C:\Users\youli\GitProject\ChatDev\chatdev\chat_env.py", line 82, in ChatEnv
    def exist_bugs(self) -> tuple[bool, str]:
TypeError: 'type' object is not subscriptable
(.venv)

**Comment by Alphamasterliu** [comment]
Hello, I have just tested the code you provided and confirmed that it does not affect ChatDev's operation. Considering that the error you encountered on line 82 appears to be related to a def function, it might be due to a Python version issue. I would recommend upgrading to Python 3.9 or a higher version. 
Thank you for your efforts in trying out ChatDev, and please feel free to continue asking if you have any further questions or issues.
