### ISSUE TITLE
Make it run in Docker by default

### ISSUE THREAD

**Issue by James4Ever0** [OpenBMB/ChatDev#125]
Any autonomous or authoritative AI agent shall be running in containers by default. Security is not something negotiable.

Security is not just prevention of backfires. It is the root of trust and large-scale evolution.

I have mentioned similar issues in [open-interpreter]() and [AutoGPT](https://github.com/Significant-Gravitas/AutoGPT).

**Comment by Acephali92** [comment]
Yeah i would be thankfull, because it allows individuals and organizations to have more control over the AI's behavior and mitigate potential risks. When people know that an AI system is secure and trustworthy, they are more likely to engage with it, fostering better connections between humans and AI.

**Comment by Raff-dev** [comment]
Is this issue worked on by anyone atm? I could tackle it.

**Comment by ManindraDeMel** [comment]
Likewise, i could work on this too with @Raff-dev please assign us this issue
