### ISSUE TITLE
Will It support gpt 4?

### ISSUE THREAD

**Issue by Am0stafa** [OpenBMB/ChatDev#127]

**Comment by hippoduck** [comment]
It already does. Use --model "GPT_4".

**Comment by TyrellR** [comment]
Do i just type that directly in the terminal?

**Comment by TyrellR** [comment]
> It already does. Use `--model "GPT_4"`.
Do i just type this directly in the terminal? or do i need a command before it?

**Comment by Am0stafa** [comment]
Will it use 32k context window ?

**Comment by delconis** [comment]
You use it as a an option when running the `run.py` e.x. `python3 run.py --task "Create a tic tak toe game using pygame" --name "tic-tak-toe" --model "GPT_4`

try `python3 run.py --help` for a full explanation. 

Note, I did find the API times out due to Token Rate limits causing the application to fail, I found a comment on the Discord with the solution they mentioned and added my own on my fork.

My PR that allows me GPT_4 to not timeout
https://github.com/OpenBMB/ChatDev/pull/140

Can you close this issue though?
