### ISSUE TITLE
Can we run on self hosted llama model ?

### ISSUE THREAD

**Issue by HarshitDaftary** [OpenBMB/ChatDev#148]
This is really great repo. I would like to learn and play around various outputs. I have locally hosted Llama model. Can you please guide me on how to use that model or Llama API that uses model hosted in my other server ?

**Comment by Alphamasterliu** [comment]
Hello!

Thank you for your support and efforts with our ChatDev project. Regarding the configuration to use language models other than OpenAI, we have not developed that feature at the moment. However, given the significant user demand, this will be one of our major feature goals in the future. We appreciate your ongoing interest, and please stay tuned for updates.

**Comment by Alphamasterliu** [comment]
Hello, after analysis, I recommend you can try referring to these two links. Although we can’t fully test these features quickly due to recent time constraints, they appear to be very valuable for reference based on the current situation.
https://github.com/OpenBMB/ChatDev/issues/27#issuecomment-1735911721; 
https://github.com/OpenBMB/ChatDev/pull/53

> This is really great repo. I would like to learn and play around various outputs. I have locally hosted Llama model. Can you please guide me on how to use that model or Llama API that uses model hosted in my other server ?
