### ISSUE TITLE
Is there anyway to add feedback after chatdev stops running and has completed the project?

### ISSUE THREAD

**Issue by notVegas** [OpenBMB/ChatDev#169]
ive just finished experimenting and gotten a project file but i need to iterate on it and point out things is this possible to do?

**Comment by brycehuston** [comment]
Same ^

**Comment by Elsayed91** [comment]
Same. You will mostly remember things you want to implement after you prompt or after you see the results, rebuilding the wheel from scratch does not sound efficient, especially since every step is tracked. The ability to add a simple extension, without having to go through the whole process from the beginning would be invaluable.

**Comment by worycatts** [comment]
See response here - https://github.com/OpenBMB/ChatDev/issues/147#issuecomment-1751994828

**Comment by Alphamasterliu** [comment]
Hello! You can enter the Human-Agent Interaction mode by adding --config "Human" while starting the "--task" phase. This way, during the initial software draft generation, you can run the main.py file and then return to the terminal to input feedback for more optimized prompts, assisting ChatDev in making improvements or adding new features. I believe that becoming proficient with this mode will help you address the issue. Thank you very much for trying out and supporting ChatDev!
