### ISSUE TITLE
More info on git_management please

### ISSUE THREAD

**Issue by djbritt** [OpenBMB/ChatDev#196]
_Originally posted by @Alphamasterliu in 
https://github.com/OpenBMB/ChatDev/issues/136#issuecomment-1751914383_

Sorry, I also would like more information about what git_management actually does, I don't think your readme or wiki explains it very well. Would you be willing to expand on what git_management offers?

September 25th, 2023: The Git feature is now available, enabling the programmer to utilize GitHub for version control. To enable this feature, simply set "git_management" to "True" in ChatChainConfig.json.

**Comment by thinkwee** [comment]
Sorry for the confusion. We will update the wiki.

**Comment by thinkwee** [comment]
We have updated the wiki, you can see introduction at https://github.com/OpenBMB/ChatDev/blob/main/wiki.md#git-mode

**Comment by djbritt** [comment]
@thinkwee Just to confirm, this might also be good to add on the readme, but the github push is only per project right? You can't have chatdev reopen a previous github repo it previously uploaded code to, right?

**Comment by thinkwee** [comment]
ChatDev can not open another git repository for the moment.  It can only add several git commits to the current software to be generated to facilitate backtracking and modification.

**Comment by djbritt** [comment]
@thinkwee I don't mean another git repo, I mean if I rerun chatdev, could it reopen the same git repo it just created in the previous run? So I could further modify the script it made?

**Comment by thinkwee** [comment]
> @thinkwee I don't mean another git repo, I mean if I rerun chatdev, could it reopen the same git repo it just created in the previous run? So I could further modify the script it made?

No, ChatDev can not reopen the same git repo because it will create a new folder with a new timestamp. However, ChatDev can be slightly modified to open an existing project and then continue with the git operation. Many users hope to have such an incremental development function, but we are still discussing the specific implementation, because everyone's specific needs for incremental development are very different, and we hope to be able to provide a more general solution.
