### ISSUE TITLE
Frontend not created

### ISSUE THREAD

**Issue by albal** [OpenBMB/ChatDev#202]
Did two runs and they completed without error.  Got all the backend code and the database schema.  Did a run using the same prompt under ChatGPT 3.5 and ChatGPT 4.  Under 3.5 the manual.md had details of setting up the frontend but there were no frontend files.  The prompt requested the the frontend should be created with React.  Under ChatGPT 4 again no files were created for the frontend but the manual this time only had details about the project and no setup instructions.

**Comment by thinkwee** [comment]
You can share the log file so that we can confirm whether this is a problem with the ChatDev process or it is the capacity limitations of LLM itself cause the output to be unreasonable.

**Comment by albal** [comment]
Log is here:
https://github.com/albal/corevoter/blob/main/corevoter_DefaultOrganization_20231021005955.log

**Comment by NA-Wen** [comment]
Thank you for providing the detailed log!
According to the log, the failure of creating frontend in code, which was attributed to the limited capacity of LLM, was detected by the 'Software Test Engineer'. But due to the limitation of the number of rounds in test phase, this failure was not fixed in the end.  
You can try:
1. set a looser limitation of the number of rounds in test and modification phase, which can be set in `ChatChainConfig.json`
2. use our new feature `incremental development` to let agents develop based on the existed backend code
3. or modify the problem by yourself
