### ISSUE TITLE
How can I config API host to my own instead of the default: https://api.openai.com ?

### ISSUE THREAD

**Issue by jjzoob** [OpenBMB/ChatDev#206]

**Comment by thinkwee** [comment]
please refer to issue #27

**Comment by Alphamasterliu** [comment]
yep, I recommend you can try referring to these two links. Although we can’t fully test these features quickly due to recent time constraints, they appear to be very valuable for reference based on the current situation.
https://github.com/OpenBMB/ChatDev/issues/27#issuecomment-1735911721;
https://github.com/OpenBMB/ChatDev/pull/53
