### ISSUE TITLE
LM Studio 

### ISSUE THREAD

**Issue by kokuAI6** [OpenBMB/ChatDev#207]
Any guidance on setting up with LM Studio API ?

**Comment by diskreet90** [comment]
#27  there's some tips on there that got it working for me. Using mistral 7b, it's alright but ChatGPT def does better

**Comment by dahifi** [comment]
The TLDR is 
```
export OPENAI_API_KEY="sk-dummy1234"
export OPENAI_API_BASE="http://localhost:1234/v1"
```

**Comment by yashkite** [comment]
In Windows PowerShell, you can set environment variables using the following commands:

```powershell
$env:OPENAI_API_KEY="sk-dummy1234"
$env:OPENAI_API_BASE="http://localhost:1234/v1"
```

This sets the `OPENAI_API_KEY` and `OPENAI_API_BASE` environment variables with the specified values. Note that there are no spaces around the equal sign, and the values are enclosed in double quotes.

Keep in mind that these changes will only persist for the duration of your PowerShell session. If you want to make them permanent, you might consider adding them to your user or system environment variables.

If you are using Command Prompt instead of PowerShell, you can use the `set` command:

```cmd
set OPENAI_API_KEY=sk-dummy1234
set OPENAI_API_BASE=http://localhost:1234/v1
```

Again, note that there are no spaces around the equal sign. Environment variable changes made in Command Prompt will also only persist for the duration of that session.

**Comment by dade6** [comment]
> ```batchfile
> set OPENAI_API_KEY=sk-dummy1234
> set OPENAI_API_BASE=http://localhost:1234/v1
> ```
> 
> Again, note that there are no spaces around the equal sign. Environment variable changes made in Command Prompt will also only persist for the duration of that session.

Hi yashkite, if i do like you suggested I get this error:
  File "C:\ProgramData\anaconda3\envs\ChatDev_conda_env\lib\site-packages\openai\_base_client.py", line 877, in _request 
raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-dummy1234. You can find your API key at https://platform.openai.com account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

Can you please help me?

**Comment by ShirakuraKeishi** [comment]
Hi @dade6 !
You may have already solved this problem, but I decided to comment for the benefit of newbies like me.
You need to rewrite the variable names slightly as follows.
`set BASE_URL=http://localhost:1234/v1`
I found a hint of the solution #312 ;)
