### ISSUE TITLE
ModuleNotFoundError: No module named 'tenacity'

### ISSUE THREAD

**Issue by gavin233333** [OpenBMB/ChatDev#285]
Hi dev team,

Thanks for making this.

I faced an issue when trying the demo when my input was "python run.py --task "a small pingpong game" --name "pingpong". It showed that "ModuleNotFoundError: No module named 'tenacity".

My environment is that windows os and python 3.10.6.

Let me know how to fix it. Thanks!

Gavin

**Comment by wyifei26** [comment]
try `pip install tenacity` in your conda env?

**Comment by cryptictech** [comment]
> try `pip install tenacity` in your conda env?

I'm also facing this issue, confirmed I have tenacity installed:

```
PS C:\Users\[user]\repo\ChatDev> pip install tenacity
Requirement already satisfied: tenacity in c:\users\[user]\miniconda3\lib\site-packages (8.2.2)
PS C:\Users\[user]\repo\ChatDev> python3 run.py --task "Create a task list backend using Rocket.rs Rust for the API and SQLX for migrations" --name "TestRust" --org "dgreen"
Traceback (most recent call last):
  File "C:\Users\[user]\repo\ChatDev\run.py", line 19, in <module>
    from camel.typing import ModelType
  File "C:\Users\[user]\repo\ChatDev\camel\__init__.py", line 14, in <module>
    import camel.agents
  File "C:\Users\[user]\repo\ChatDev\camel\agents\__init__.py", line 15, in <module>
    from .chat_agent import ChatAgent
  File "C:\Users\[user]\repo\ChatDev\camel\agents\chat_agent.py", line 17, in <module>
    from tenacity import retry
ModuleNotFoundError: No module named 'tenacity'
```

**Comment by JiahaoLi2003** [comment]
try use：python run.py --task "[description_of_your_idea]" --name "[project_name]"
instead of：python3 run.py --task "[description_of_your_idea]" --name "[project_name]"

**Comment by Cha-Ching13** [comment]
I'm not sure that I've got it solved yet but I have the exact same issue and I think I'm on the right track. I'll reply to my comment with how things go.

Change your directory to where the issue lies which actually seems to be that there is no "chat_agent" for tenacity to be received from.
CD **D:\Programs-AI\**ChatDev\camel\agents
Replace **D:\Programs-AI** with whatever your terminal is already saying

Then 
pip install chat_agent

This is where I'm at now. When I open chat_agent in notepad, it's still saying to import tenacity so I don't know if this will get me anywhere. I'm new to this with no coding experience and just trying to stumble onto the right thing

**Comment by AyabongaQwabi** [comment]
Same her I'm on Mac OS Ventura
