### ISSUE TITLE
state=finished raised RateLimitError

### ISSUE THREAD

**Issue by ice-ux** [OpenBMB/ChatDev#286]
tenacity.RetryError: RetryError[<Future at 0x1c7385c4820 state=finished raised RateLimitError>]

**Comment by BackMountainDevil** [comment]
paste all terminal output

**Comment by Alphamasterliu** [comment]
Hello,
When you're troubleshooting the error in the program, you should investigate the line before 
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
```
in the terminal output. This line usually contains the exact statement that led to the error and will be crucial for identifying the root cause of the problem.

If you have any specific questions or require further assistance, do not hesitate to raise them! Thank you for your support and interest in ChatDev.
