### ISSUE TITLE
Clarify what the display/IP is for in the Docker runner

### ISSUE THREAD

**Issue by DeflateAwning** [OpenBMB/ChatDev#290]
In the [Docker run instructions](https://github.com/OpenBMB/ChatDev/blob/main/wiki.md#run-docker), what is the `YOUR_IP` for? Why is it required _within_ the Docker container?

That sorta goes against the whole point of Docker, as far as I know.

At the very least, the linked section should explain what happens if that part is omitted

**Comment by thinkwee** [comment]
<img width="1079" alt="image" src="https://github.com/OpenBMB/ChatDev/assets/11889052/a07b96ae-480d-4a60-be02-aad2cf12edf1">

the definition of YOUR_IP is mentioned above in the wiki, i.e. the address of inet.

This design of communicating with external servers does violate Docker's design principles.

We needed this because ChatDev would run the generated GUI software for automated testing and debugging, and there was no way to run graphical interface programs within docker, so we settled for this XQuartz-based docker solution.

If you have a better plan, please let us know, thank you ~

**Comment by DeflateAwning** [comment]
"inet address" is not a standard term. Is this your internal IP. What is it going to do when you enter it. My questions still stand.

> We needed this because ChatDev would run the generated GUI software for automated testing and debugging, and there was no way to run graphical interface programs within docker, so we settled for this XQuartz-based docker solution.

This answers my question. This should be explained in the wiki in that section.

What library is this "gui" being run on? Why does it need to run at all? Where in the code is the GUI being instantiated?

**Comment by DeflateAwning** [comment]
It's too bad this issue got closed, as no action was taken to clarify the answers in the repo, and no response was given to my last question. Please consider re-opening it until it is handled appropriately.
