### ISSUE TITLE
File Upload Button In Replay.html is not working 

### ISSUE THREAD

**Issue by abhinav6767** [OpenBMB/ChatDev#58]

**Comment by NA-Wen** [comment]
Could you please provide more detailed information about the problem?

**Comment by timcperks** [comment]
I run the app.py and get no errors but the upload button does nothing

**Comment by timcperks** [comment]
> Could you please provide more detailed information about the problem?

I run the app.py and get no errors but the upload button does nothing

**Comment by NA-Wen** [comment]
> > Could you please provide more detailed information about the problem?
> 
> I run the app.py and get no errors but the upload button does nothing

Running `app.py` means you start the flask app. It will automatically display the chat process being generated, with no need to clicking or uploading. If you want to use the replay.html, you need to click `file upload ` button and choose a local log file, then click `replay` button. Then the chat log will be replayed in the right side. 
More detailed information about the local demo is in our wiki  
[local demo](https://github.com/OpenBMB/ChatDev/blob/main/wiki.md#local-demo)

**Comment by FranM2030** [comment]
the 'file upload' button does not work on windows, so you can't load a log

**Comment by timcperks** [comment]
> the 'file upload' button does not work on windows, so you can't load a log

Am on ubuntu. not working here either

**Comment by timcperks** [comment]
> > > Could you please provide more detailed information about the problem?
> > 
> > 
> > I run the app.py and get no errors but the upload button does nothing
> 
> Running `app.py` means you start the flask app. It will automatically display the chat process being generated, with no need to clicking or uploading. If you want to use the replay.html, you need to click `file upload ` button and choose a local log file, then click `replay` button. Then the chat log will be replayed in the right side. More detailed information about the local demo is in our wiki [local demo](https://github.com/OpenBMB/ChatDev/blob/main/wiki.md#local-demo)

Lol, bro, if it did that then I wouldn't be here bugging you.

**Comment by NA-Wen** [comment]
More information about the problem is needed for we do not know the exact scenario where the error occured. 
1. Which browser are you using ,inlcuding type and version ?
2. Could you please provide some screen shots or description about your operating process about using `replay.html`? 
@timcperks @abhinav6767 @FranM2030

**Comment by timcperks** [comment]
Tried firefox, chromium, brave all on ubuntu. Latest updates. bro, its a button . . . how do i screenshot a button that doesnt work? I see button. I press button. nothin. Thats the whole error.

**Comment by chuyqa** [comment]
I had a similar issue, and noticed the jquery lib was timing out from baidu
https://github.com/OpenBMB/ChatDev/blob/535921ebae39643f10606ae0337294fc6a3a609a/online_log/static/replay.html#L3
fwiw changing it to a cloudflare cdn made it progress for me. 
https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js

**Comment by NA-Wen** [comment]
> I had a similar issue, and noticed the jquery lib was timing out from baidu
> 
> https://github.com/OpenBMB/ChatDev/blob/535921ebae39643f10606ae0337294fc6a3a609a/online_log/static/replay.html#L3
> 
> 
> fwiw changing it to a cloudflare cdn made it progress for me.
> https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js

Thank you for providing suggestions to help solve this hard-to-locate issue(in fact we've tested this html on more than three devices and different systems for this issue).  Could you please propose a pull request about this ? @chuyqa

**Comment by mferris77** [comment]
FWIW I ran into this issue as well, but it's likely because I am on my work network, running ChatDev in a windows VM, and the error I was getting was something about the request being blocked due to certificate authority issues.  I just downloaded both files that were included as HTTPS URLs, placed them in the /replay/js folder, and updated the script src references - from there it worked.

And I must say - I've tried a handful of these AI tools (AutoGPT, GPT Engineer, AutoGen, etc) and this is the first one that created an actual working application right off the bat.  The only setup issue I had was what I just mentioned above.  I asked 'the team' to create an html page with a text input field that would autosuggest words from a predefined list (sort of like when you're typing in a google search) - with the added requirement that it account for typographical errors.  Oh actually there was one other error in that it correctly implemented the fuse.js library but 'forgot'  to download the .js file to the directory.  Once I placed that file in the folder where it was expected to be, the solution worked flawlessly.

**Comment by vonisok** [comment]
> Tried firefox, chromium, brave all on ubuntu. Latest updates. bro, its a button . . . how do i screenshot a button that doesnt work? I see button. I press button. nothin. Thats the whole error.

I had the same problem. Used Chrome and fixed it. Possibly a setting in your browser preventing the pop up window to upload.
