### ISSUE TITLE
support claude 2, and support auto analysis github repo and write code based on public repo

### ISSUE THREAD

**Issue by zeliansiji** [OpenBMB/ChatDev#73]
support claude 2, and support auto analysis github repo and write code based on public repo

**Comment by Alphamasterliu** [comment]
Hello! Regarding the configuration for using other models, you may want to try out this PR#53. You can find the link here: https://github.com/OpenBMB/ChatDev/pull/53. While our team hasn't fully tested it due to time constraints, it has received positive feedback for its effectiveness. Thank you very much for your support and attention to ChatDev. Please feel free to raise any questions or ideas, and we'll do our best to address your needs and continue improving our product.
