### ISSUE TITLE
Repeated texts in replay and log

### ISSUE THREAD

**Issue by william2313** [OpenBMB/ChatDev#89]
The replay/logs seem to contain an awful lot of repeating steps. Agents say the same things over and over again, the same files get modified in the same way multiple times, etc.  This makes reading the replay/logs completely impractical.

**Comment by william2313** [comment]
Yeah as I said, it also happens in the log. 
I counted the text "[ChatDev is a software company powered by multiple intelligent agents..." about 40 times.

**Comment by Dartomic** [comment]
I'm not sure, but I assume this happens due to the GPT model not having memory of previous prompts and what it has output. So I think it does this in order to bring the chatbot up to date in the part of the conversation that is actually the part that is in progress, since using the API relies on the prompts to serve as the memory of the conversations. I might be wrong, but I am pretty sure it has no other way of knowing what it was previously prompted with, and no way of knowing what it has previously output either.

**Comment by william2313** [comment]
I see, I wasn't aware yet of the API keeping no memory of conversations.
Maybe it's an idea to just exclude all these "memory" parts of the prompts from the log (or from a separate version of the log).

**Comment by thinkwee** [comment]
@william2313  It is not a repetition bug. The text you mentioned is a role play background prompt that will be shown to agents every time when they make a response in the chatting.

**Comment by william2313** [comment]
I know it's not a bug. I'm just suggesting that, as a feature, it would be very useful to have a log/replay without all that background/memory text. Try to read through a project's log and you will see what I mean.

**Comment by Alphamasterliu** [comment]
Thank you for your suggestion, it is under consideration. Please look forward to our future updates.

> I know it's not a bug. I'm just suggesting that, as a feature, it would be very useful to have a log/replay without all that background/memory text. Try to read through a project's log and you will see what I mean.
